name: Build & Deploy Java Application
on: 
  push:
    branches:
      - main
jobs:
  Build_And_Deploy:
    runs-on: ubuntu-latest
    steps:

    -
      name: Checkout From Repository
      uses: actions/checkout@v2
      with:
        ref: main


