name: Build & Deploy Java Application
on:
  push:
    branches:
      - main
jobs:
  Build_And_Deploy:
    runs-on: ubuntu-latest
    steps:

    -
      name: Checkout From Repository
      uses: actions/checkout@v2
      with:
        ref: main

    -
      name: Set up JDK Environment With Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    -
      name: Test & Build Application With Maven
      run: ./mvnw package

    -
      name: Debuging the target folder
      run: pwd && ls -lha target/quarkus-app/*

    -
        name: Set up QEMU for multiple platform builds
        uses: docker/setup-qemu-action@v2

    -
        name: Set up Docker Buildx to build application
        uses: docker/setup-buildx-action@v1

    # -
    #     name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    -
        name: Build and push to dockerhub
        uses: docker/build-push-action@v1
        with:
          push: true
          repository: kr00deapp/e-transact-devops
          tags: 001-SNAPSHOT-${{github.run_number}}

    # -
    #   name: Build Docker Image
    #   run: docker build -t kr00deapp/e-transact-devops:devops-test-jvm-SNAPSHOT-${{github.run_number}} .

    # -
    #   name: Push Build To DockerHub
    #   run: docker push kr00deapp/e-transact-devops:devops-test-jvm-SNAPSHOT-${{github.run_number}}


    # -
    #   name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}







