name: Build & Deploy Java Application
on:
  push:
    branches:
      - main
jobs:
  Build_And_Deploy:
    runs-on: ubuntu-latest
    steps:

    -
    # Checking out from Git Repository
      name: Checkout From Repository
      uses: actions/checkout@v3
      with:
        ref: main

    -
    # Setting Up The JDK Environment Using Java 17
      name: Set up JDK Environment With Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    -
    # Packaging The Application
      name: Test & Package Application With Maven
      run: ./mvnw package


    -
    # Troubleshooting The Contents Of The Debug Directory
      name: Debuging the target folder
      run: |
        pwd && ls -lha target/quarkus-app/*
        pwd && ls -lha .

    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
        name: Build and push to dockerhub
        uses: docker/build-push-action@v4
        with:
          push: true
          context: src/main/docker
          # repository: kr00deapp/e-transact-devops
          tags: kr00deapp/e-transact-devops:001-SNAPSHOT-${{github.run_number}}

    # -
    #   name: Build Docker Image
    #   run: docker buildx build --platform linux/arm64 -t kr00deapp/e-transact-devops:1.0.0-SNAPSHOT-${{github.run_number}} .

    # -
    #   name: Push Build To DockerHub
    #   run: docker push kr00deapp/e-transact-devops:1.0.0-SNAPSHOT-${{github.run_number}}


    # -
    #   name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}







