name: Build & Deploy Java Application
on: 
  push:
    branches:
      - main
jobs:
  Build_And_Deploy:
    runs-on: ubuntu-latest
    steps:

    -
      name: Checkout From Repository
      uses: actions/checkout@v2
      with:
        ref: main

    -
      name: Set up JDK Environment With Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    -
      name: Build Application With Maven
      run: ./mvnw package

    -
      name: Debuging the target folder
      run: pwd && ls -lha target/quarkus-app/* 

    -
        name: Set up QEMU for multiple platform builds
        uses: docker/setup-qemu-action@v2

    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
        name: Build and push to dockerhub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kr00deapp/devops-test-jvm:${{github.run_number}}






