name: Build & Deploy Java Application
on: 
  push:
    branches:
      - main
jobs:
  Build_And_Deploy:
    runs-on: ubuntu-latest
    steps:

    -
      name: Checkout From Repository
      uses: actions/checkout@v2
      with:
        ref: main

    -
      name: Set up JDK Environment With Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    -
      name: Build Application With Maven
      run: ./mvnw package

