name: Build & Deploy Java Application
on:
  push:
    branches:
      - main
jobs:
  Build_And_Deploy:
    runs-on: ubuntu-latest
    steps:

    -
    # Checking out from Git Repository
      name: Checkout From Repository
      uses: actions/checkout@v3
      with:
        ref: main

    -
    # Setting Up The JDK Environment Using Java 17
      name: Set up JDK Environment With Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    -
    # Packaging The Application
      name: Test & Build Application With Maven
      run: ./mvnw package


    -
    # Troubleshooting The Contents Of The Debug Directory
      name: Debuging the target folder
      run: pwd && ls -lha target/quarkus-app/*

    -
        # Caching Docker Layers For Faster Consequent Builds
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # -
    #   name: Docker Login
    #   run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    # -
    #     name: Build and push to dockerhub
    #     uses: docker/build-push-action@v1
    #     with:
    #       push: true
    #       cache-from: type=local,src=/tmp/.buildx-cache
    #       cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    #       repository: kr00deapp/e-transact-devops
    #       tags: kr00deapp/e-transact-devops:001-SNAPSHOT-${{github.run_number}}

    # -
    #     # Temp fix For Caching Build Data
    #     # https://github.com/docker/build-push-action/issues/252
    #     # https://github.com/moby/buildkit/issues/1896
    #     name: Move cache
    #     run: |
    #       rm -rf /tmp/.buildx-cache
    #       mv /tmp/.buildx-cache-new /tmp/.buildx-cache


    -
      name: Build Docker Image
      run: docker build --platform linux/amd64 -t kr00deapp/e-transact-devops:1.0.0-SNAPSHOT-${{github.run_number}} .

    -
      name: Push Build To DockerHub
      run: docker push kr00deapp/e-transact-devops:1.0.0-SNAPSHOT-${{github.run_number}}


    # -
    #   name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}







